name: build
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: winebarrel/lastcmt@v0.6.0
      - run: |
          echo test | lastcmnt ${{ github.event.number }} 
